server:
  port: 8080
axon:
  snapshot:
    count: 50
  axonserver:
    servers: dev-geon-axonserver-ncl.nfra.io
spring:
  data:
    mongodb:
      host: dev-geon-mongo-ncl.nfra.io
      port: 27017
  application:
    name: query-demo