application:
  name: query-demo
axon:
  axonserver:
    servers: dev-geon-axonserver-ncl.nfra.io
spring:
  data:
    es:
      host: dev-geon-es001-ncl.nfra.io
      port: 9300
      clusterName: msa-study
server:
  port: 8080