application:
  name: command-demo
javamelody:
  advisor-auto-proxy-creator-enabled: false
axon:
  snapshot:
    count: 50
  axonserver:
    servers: dev-geon-axonserver-ncl.nfra.io
server:
  port: 9090